apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: home-ops
spec:
  type: url
  targets:
    - https://gitlab.com/iamcto/homelab/-/blob/main/.backstage/domains/denum/catalog-info.yaml
