---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: nas
  description: Synology DS920+
  annotations:
    backstage.io/techdocs-ref: dir:.
    # github.com/project-slug: tyriis/home-ops
  links:
    - url: https://synology-nas.iamcto.ru
      title: nas
      icon: dashboard
      type: admin-dashboard
  tags:
    - nas
    - nfs
    - backup
    - storage
spec:
  owner: home-ops
  domain: home
  type: storage
  lifecycle: production
  system: nas